name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: OrchardCMS/OrchardCore/.github/actions/setup-dotnet@bee407c6f0270ae94e1932c5e6719983cafa088c # main

      - name: Build
        run: dotnet build ./OrchardCore.Web/OrchardCore.Web.csproj --configuration Release

      - name: Publish
        run: dotnet publish ./OrchardCore.Web/OrchardCore.Web.csproj --configuration Release --output "${{env.DOTNET_ROOT}}/publish"

      - name: Upload Publish Package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: publish-package
          path: ${{env.DOTNET_ROOT}}/publish

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download Publish Package
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: publish-package
      
      # Stopping the app with an app_offline.htm file. Without this, files will remain locked and the deployment will
      # fail with a generic error.
      - name: Deploy App Offline to Azure Web App
        uses: azure/webapps-deploy@02a81bead70021f5284939794bcec79c271ab383 # v3
        with:
          app-name: 'orchardcoredotnet'
          slot-name: 'Production'
          package: AppOffline
          publish-profile: ${{ secrets.ORCHARDCOREDOTNET_PUBLISH_PROFILE }}
          clean: false

      - name: Deploy Website to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@02a81bead70021f5284939794bcec79c271ab383 # v3
        with:
          app-name: 'orchardcoredotnet'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.ORCHARDCOREDOTNET_PUBLISH_PROFILE }}
          # Clean deployments would wipe all files from the server, deleting the SQLite DB and Media files too.
          clean: false

